window.akhlaq = [

{ q:"Berkata jujur disebut?", A:"Amanah", B:"Shiddiq", C:"Tabligh", D:"Fathonah", correct:"B" },
{ q:"Menepati janji termasuk akhlak?", A:"Buruk", B:"Tercela", C:"Terpuji", D:"Biasa", correct:"C" },
{ q:"Berkata kasar termasuk akhlak?", A:"Baik", B:"Terpuji", C:"Buruk", D:"Mulia", correct:"C" },
{ q:"Menghormati orang tua disebut?", A:"Durhaka", B:"Birrul walidain", C:"Hasad", D:"Takabur", correct:"B" },
{ q:"Suka menolong disebut?", A:"Egois", B:"Tolong-menolong", C:"Hasad", D:"Riya", correct:"B" },
{ q:"Orang yang sombong disebut?", A:"Tawadhu", B:"Takabur", C:"Sabar", D:"Ikhlas", correct:"B" },
{ q:"Rendah hati disebut?", A:"Takabur", B:"Tawadhu", C:"Hasad", D:"Riya", correct:"B" },
{ q:"Iri terhadap orang lain disebut?", A:"Ikhlas", B:"Hasad", C:"Sabar", D:"Syukur", correct:"B" },
{ q:"Bersyukur artinya?", A:"Mengeluh", B:"Berterima kasih", C:"Marah", D:"Sombong", correct:"B" },
{ q:"Sabar artinya?", A:"Menyerah", B:"Menahan diri", C:"Marah", D:"Menghina", correct:"B" },
{ q:"Berbuat baik kepada teman termasuk?", A:"Akhlak buruk", B:"Akhlak tercela", C:"Akhlak terpuji", D:"Akhlak biasa", correct:"C" },
{ q:"Meminta maaf adalah sikap?", A:"Sombong", B:"Terpuji", C:"Buruk", D:"Hasad", correct:"B" },
{ q:"Menghina teman termasuk?", A:"Baik", B:"Terpuji", C:"Buruk", D:"Mulia", correct:"C" },
{ q:"Memberi salam adalah akhlak?", A:"Buruk", B:"Terpuji", C:"Tercela", D:"Biasa", correct:"B" },
{ q:"Membuang sampah sembarangan termasuk?", A:"Baik", B:"Terpuji", C:"Buruk", D:"Mulia", correct:"C" },
{ q:"Menolong teman yang kesulitan adalah?", A:"Akhlak buruk", B:"Akhlak tercela", C:"Akhlak terpuji", D:"Akhlak biasa", correct:"C" },
{ q:"Berbohong termasuk?", A:"Akhlak baik", B:"Akhlak mulia", C:"Akhlak buruk", D:"Akhlak terpuji", correct:"C" },
{ q:"Ikhlas artinya?", A:"Pamer", B:"Tulus", C:"Sombong", D:"Marah", correct:"B" },
{ q:"Riya artinya?", A:"Tulus", B:"Pamer", C:"Sabar", D:"Ikhlas", correct:"B" },
{ q:"Meminta izin sebelum masuk rumah termasuk?", A:"Akhlak buruk", B:"Akhlak terpuji", C:"Akhlak tercela", D:"Akhlak biasa", correct:"B" },
{ q:"Mencuri termasuk akhlak?", A:"Baik", B:"Terpuji", C:"Buruk", D:"Mulia", correct:"C" },
{ q:"Mengucapkan terima kasih adalah?", A:"Buruk", B:"Terpuji", C:"Tercela", D:"Biasa", correct:"B" },
{ q:"Berbicara sopan adalah?", A:"Akhlak buruk", B:"Akhlak terpuji", C:"Akhlak tercela", D:"Akhlak biasa", correct:"B" },
{ q:"Memukul teman termasuk?", A:"Baik", B:"Terpuji", C:"Buruk", D:"Mulia", correct:"C" },
{ q:"Berbagi dengan teman adalah?", A:"Akhlak buruk", B:"Akhlak tercela", C:"Akhlak terpuji", D:"Akhlak biasa", correct:"C" },
{ q:"Meminta maaf saat salah adalah sikap?", A:"Sombong", B:"Terpuji", C:"Buruk", D:"Hasad", correct:"B" },
{ q:"Mengucapkan salam saat bertemu termasuk?", A:"Akhlak buruk", B:"Akhlak terpuji", C:"Akhlak tercela", D:"Biasa", correct:"B" },
{ q:"Mendengarkan saat orang lain bicara adalah?", A:"Buruk", B:"Terpuji", C:"Tercela", D:"Biasa", correct:"B" },
{ q:"Memotong pembicaraan orang lain termasuk?", A:"Baik", B:"Terpuji", C:"Buruk", D:"Mulia", correct:"C" },
{ q:"Menghargai pendapat teman adalah?", A:"Akhlak buruk", B:"Akhlak tercela", C:"Akhlak terpuji", D:"Biasa", correct:"C" },
{ q:"Tidak sombong saat berhasil disebut?", A:"Takabur", B:"Tawadhu", C:"Hasad", D:"Riya", correct:"B" },
{ q:"Membantu orang tua di rumah adalah?", A:"Buruk", B:"Terpuji", C:"Tercela", D:"Biasa", correct:"B" },
{ q:"Melawan orang tua termasuk?", A:"Baik", B:"Terpuji", C:"Buruk", D:"Mulia", correct:"C" },
{ q:"Mengucapkan salam saat masuk rumah adalah?", A:"Buruk", B:"Terpuji", C:"Tercela", D:"Biasa", correct:"B" },
{ q:"Berterima kasih atas bantuan orang lain adalah?", A:"Akhlak buruk", B:"Akhlak terpuji", C:"Akhlak tercela", D:"Biasa", correct:"B" },
{ q:"Menyakiti teman termasuk?", A:"Baik", B:"Terpuji", C:"Buruk", D:"Mulia", correct:"C" },
{ q:"Menepati janji adalah sikap?", A:"Buruk", B:"Terpuji", C:"Tercela", D:"Biasa", correct:"B" },
{ q:"Menghormati guru termasuk?", A:"Akhlak buruk", B:"Akhlak tercela", C:"Akhlak terpuji", D:"Biasa", correct:"C" },
{ q:"Tidak mau berbagi adalah sikap?", A:"Baik", B:"Terpuji", C:"Buruk", D:"Mulia", correct:"C" },
{ q:"Memberi bantuan tanpa pamrih disebut?", A:"Riya", B:"Ikhlas", C:"Takabur", D:"Hasad", correct:"B" },
{ q:"Mengejek teman termasuk?", A:"Baik", B:"Terpuji", C:"Buruk", D:"Mulia", correct:"C" },
{ q:"Berdoa sebelum belajar termasuk?", A:"Buruk", B:"Terpuji", C:"Tercela", D:"Biasa", correct:"B" },
{ q:"Membantu teman belajar adalah?", A:"Akhlak buruk", B:"Akhlak tercela", C:"Akhlak terpuji", D:"Biasa", correct:"C" },
{ q:"Menjaga kebersihan adalah?", A:"Buruk", B:"Terpuji", C:"Tercela", D:"Biasa", correct:"B" },
{ q:"Membuang sampah pada tempatnya adalah?", A:"Akhlak buruk", B:"Akhlak tercela", C:"Akhlak terpuji", D:"Biasa", correct:"C" },
{ q:"Berbohong kepada orang tua termasuk?", A:"Baik", B:"Terpuji", C:"Buruk", D:"Mulia", correct:"C" },
{ q:"Meminta izin sebelum memakai barang orang lain adalah?", A:"Buruk", B:"Terpuji", C:"Tercela", D:"Biasa", correct:"B" },
{ q:"Mengganggu teman belajar termasuk?", A:"Baik", B:"Terpuji", C:"Buruk", D:"Mulia", correct:"C" },
{ q:"Mengucapkan maaf saat bersalah adalah?", A:"Akhlak buruk", B:"Akhlak tercela", C:"Akhlak terpuji", D:"Biasa", correct:"C" },
{ q:"Saling tolong menolong disebut?", A:"Hasad", B:"Ta'awun", C:"Takabur", D:"Riya", correct:"B" },
{ q:"Mengucapkan salam saat bertemu teman adalah?", A:"Buruk", B:"Terpuji", C:"Tercela", D:"Biasa", correct:"B" },
{ q:"Menolong orang tanpa mengharap balasan disebut?", A:"Riya", B:"Ikhlas", C:"Takabur", D:"Hasad", correct:"B" },
{ q:"Tidak mudah marah termasuk sifat?", A:"Buruk", B:"Terpuji", C:"Tercela", D:"Biasa", correct:"B" },
{ q:"Mengendalikan emosi disebut?", A:"Sabar", B:"Takabur", C:"Hasad", D:"Riya", correct:"A" },
{ q:"Menghormati orang yang lebih tua adalah?", A:"Akhlak buruk", B:"Akhlak tercela", C:"Akhlak terpuji", D:"Biasa", correct:"C" },
{ q:"Membantah guru termasuk?", A:"Baik", B:"Terpuji", C:"Buruk", D:"Mulia", correct:"C" },
{ q:"Mengucapkan terima kasih saat diberi sesuatu adalah?", A:"Buruk", B:"Terpuji", C:"Tercela", D:"Biasa", correct:"B" },
{ q:"Mengganggu orang lain termasuk?", A:"Baik", B:"Terpuji", C:"Buruk", D:"Mulia", correct:"C" },
{ q:"Berbicara dengan lembut adalah?", A:"Akhlak buruk", B:"Akhlak tercela", C:"Akhlak terpuji", D:"Biasa", correct:"C" },
{ q:"Menyapa teman dengan ramah termasuk?", A:"Buruk", B:"Terpuji", C:"Tercela", D:"Biasa", correct:"B" },
{ q:"Menyembunyikan kesalahan teman termasuk?", A:"Akhlak buruk", B:"Akhlak terpuji", C:"Akhlak tercela", D:"Biasa", correct:"B" },
{ q:"Menyebarkan aib teman termasuk?", A:"Baik", B:"Terpuji", C:"Buruk", D:"Mulia", correct:"C" },
{ q:"Mengalah demi kebaikan disebut?", A:"Sabar", B:"Takabur", C:"Hasad", D:"Riya", correct:"A" },
{ q:"Tidak membalas kejahatan dengan kejahatan adalah?", A:"Akhlak buruk", B:"Akhlak terpuji", C:"Akhlak tercela", D:"Biasa", correct:"B" },
{ q:"Meminta maaf dengan tulus adalah?", A:"Buruk", B:"Terpuji", C:"Tercela", D:"Biasa", correct:"B" },
{ q:"Menghargai perbedaan adalah?", A:"Akhlak buruk", B:"Akhlak tercela", C:"Akhlak terpuji", D:"Biasa", correct:"C" },
{ q:"Mengucapkan salam saat masuk rumah adalah?", A:"Buruk", B:"Terpuji", C:"Tercela", D:"Biasa", correct:"B" },
{ q:"Menolong teman tanpa disuruh adalah?", A:"Akhlak buruk", B:"Akhlak tercela", C:"Akhlak terpuji", D:"Biasa", correct:"C" },
{ q:"Menghormati tetangga adalah?", A:"Buruk", B:"Terpuji", C:"Tercela", D:"Biasa", correct:"B" },
{ q:"Mengucapkan kata kasar termasuk?", A:"Baik", B:"Terpuji", C:"Buruk", D:"Mulia", correct:"C" },
{ q:"Bersikap ramah kepada semua orang adalah?", A:"Akhlak buruk", B:"Akhlak tercela", C:"Akhlak terpuji", D:"Biasa", correct:"C" },
{ q:"Menolong orang tua tanpa disuruh adalah?", A:"Buruk", B:"Terpuji", C:"Tercela", D:"Biasa", correct:"B" },
{ q:"Mengucapkan salam saat berpisah adalah?", A:"Buruk", B:"Terpuji", C:"Tercela", D:"Biasa", correct:"B" },
{ q:"Tidak menyela pembicaraan orang lain adalah?", A:"Akhlak buruk", B:"Akhlak tercela", C:"Akhlak terpuji", D:"Biasa", correct:"C" },
{ q:"Menjaga ucapan agar tidak menyakiti adalah?", A:"Buruk", B:"Terpuji", C:"Tercela", D:"Biasa", correct:"B" },
{ q:"Menghormati orang tua disebut?", A:"Hasad", B:"Birrul walidain", C:"Riya", D:"Takabur", correct:"B" },
{ q:"Tidak sombong saat memiliki kelebihan adalah?", A:"Takabur", B:"Tawadhu", C:"Hasad", D:"Riya", correct:"B" },
{ q:"Mengucapkan terima kasih setelah ditolong adalah?", A:"Buruk", B:"Terpuji", C:"Tercela", D:"Biasa", correct:"B" },
{ q:"Mengolok-olok teman termasuk?", A:"Baik", B:"Terpuji", C:"Buruk", D:"Mulia", correct:"C" },
{ q:"Berbuat baik kepada tetangga adalah?", A:"Akhlak buruk", B:"Akhlak tercela", C:"Akhlak terpuji", D:"Biasa", correct:"C" },
{ q:"Tidak berkata kasar adalah sikap?", A:"Buruk", B:"Terpuji", C:"Tercela", D:"Biasa", correct:"B" },
{ q:"Menghargai bantuan orang lain adalah?", A:"Akhlak buruk", B:"Akhlak terpuji", C:"Akhlak tercela", D:"Biasa", correct:"B" },
{ q:"Mengucapkan maaf setelah berbuat salah adalah?", A:"Buruk", B:"Terpuji", C:"Tercela", D:"Biasa", correct:"B" },
{ q:"Menyakiti hati orang lain termasuk?", A:"Baik", B:"Terpuji", C:"Buruk", D:"Mulia", correct:"C" },
{ q:"Bersikap sopan kepada guru adalah?", A:"Akhlak buruk", B:"Akhlak tercela", C:"Akhlak terpuji", D:"Biasa", correct:"C" },
{ q:"Tidak membalas ejekan adalah sikap?", A:"Buruk", B:"Terpuji", C:"Tercela", D:"Biasa", correct:"B" },
{ q:"Berbicara jujur kepada siapa pun adalah?", A:"Akhlak buruk", B:"Akhlak terpuji", C:"Akhlak tercela", D:"Biasa", correct:"B" },
{ q:"Menghormati teman adalah?", A:"Buruk", B:"Terpuji", C:"Tercela", D:"Biasa", correct:"B" },
{ q:"Mengucapkan salam kepada orang lain adalah?", A:"Akhlak buruk", B:"Akhlak terpuji", C:"Akhlak tercela", D:"Biasa", correct:"B" },
{ q:"Menjaga kebersihan diri adalah?", A:"Buruk", B:"Terpuji", C:"Tercela", D:"Biasa", correct:"B" },
{ q:"Tidak iri kepada teman adalah sikap?", A:"Hasad", B:"Ikhlas", C:"Riya", D:"Takabur", correct:"B" },
{ q:"Memaafkan kesalahan orang lain adalah?", A:"Akhlak buruk", B:"Akhlak terpuji", C:"Akhlak tercela", D:"Biasa", correct:"B" },
{ q:"Menyapa orang dengan ramah adalah?", A:"Buruk", B:"Terpuji", C:"Tercela", D:"Biasa", correct:"B" },
{ q:"Menghargai waktu adalah?", A:"Akhlak buruk", B:"Akhlak terpuji", C:"Akhlak tercela", D:"Biasa", correct:"B" },
{ q:"Menghindari perbuatan dosa adalah?", A:"Buruk", B:"Terpuji", C:"Tercela", D:"Biasa", correct:"B" },
{ q:"Berbuat baik kepada semua orang adalah?", A:"Akhlak buruk", B:"Akhlak terpuji", C:"Akhlak tercela", D:"Biasa", correct:"B" },
{ q:"Tidak sombong kepada siapa pun adalah?", A:"Takabur", B:"Tawadhu", C:"Hasad", D:"Riya", correct:"B" },
{ q:"Menghormati perbedaan adalah?", A:"Buruk", B:"Terpuji", C:"Tercela", D:"Biasa", correct:"B" },
{ q:"Menolong tanpa pamrih adalah?", A:"Riya", B:"Ikhlas", C:"Hasad", D:"Takabur", correct:"B" },
{ q:"Menghindari perkataan buruk adalah?", A:"Akhlak buruk", B:"Akhlak terpuji", C:"Akhlak tercela", D:"Biasa", correct:"B" }

];