window.aqidah = [

{ q:"Allah Maha Esa disebut?", A:"Rahman", B:"Ahad", C:"Malik", D:"Quddus", correct:"B" },
{ q:"Jumlah rukun iman ada?", A:"4", B:"5", C:"6", D:"7", correct:"C" },
{ q:"Iman kepada malaikat termasuk rukun iman ke?", A:"1", B:"2", C:"3", D:"4", correct:"B" },
{ q:"Kitab Allah yang terakhir adalah?", A:"Injil", B:"Zabur", C:"Taurat", D:"Al-Qur'an", correct:"D" },
{ q:"Nabi terakhir adalah?", A:"Isa", B:"Musa", C:"Muhammad", D:"Ibrahim", correct:"C" },
{ q:"Allah Maha Mengetahui disebut?", A:"Al-Alim", B:"Al-Malik", C:"As-Salam", D:"Al-Quddus", correct:"A" },
{ q:"Iman kepada hari akhir artinya percaya?", A:"Surga", B:"Kematian", C:"Hari kiamat", D:"Malaikat", correct:"C" },
{ q:"Allah Maha Pengasih disebut?", A:"Ar-Rahman", B:"Al-Malik", C:"Al-Aziz", D:"Al-Hakim", correct:"A" },
{ q:"Allah Maha Penyayang disebut?", A:"Ar-Rahim", B:"Al-Alim", C:"Al-Khaliq", D:"Al-Qadir", correct:"A" },
{ q:"Iman kepada takdir disebut?", A:"Qada dan Qadar", B:"Ijtihad", C:"Shalat", D:"Zakat", correct:"A" },
{ q:"Jumlah malaikat wajib diketahui?", A:"5", B:"10", C:"15", D:"20", correct:"B" },
{ q:"Malaikat pencatat amal baik adalah?", A:"Jibril", B:"Mikail", C:"Raqib", D:"Atid", correct:"C" },
{ q:"Malaikat pencatat amal buruk adalah?", A:"Raqib", B:"Atid", C:"Ridwan", D:"Malik", correct:"B" },
{ q:"Malaikat penyampai wahyu adalah?", A:"Mikail", B:"Israfil", C:"Jibril", D:"Izrail", correct:"C" },
{ q:"Allah Maha Kuasa disebut?", A:"Al-Qadir", B:"Al-Hakim", C:"Al-Aziz", D:"Al-Latif", correct:"A" },
{ q:"Percaya kepada rasul termasuk rukun iman ke?", A:"2", B:"3", C:"4", D:"5", correct:"C" },
{ q:"Kitab Zabur diturunkan kepada nabi?", A:"Musa", B:"Isa", C:"Daud", D:"Muhammad", correct:"C" },
{ q:"Kitab Taurat diturunkan kepada?", A:"Isa", B:"Musa", C:"Daud", D:"Nuh", correct:"B" },
{ q:"Kitab Injil diturunkan kepada?", A:"Musa", B:"Isa", C:"Muhammad", D:"Ibrahim", correct:"B" },
{ q:"Allah Maha Melihat disebut?", A:"As-Sami", B:"Al-Basir", C:"Al-Alim", D:"Al-Khaliq", correct:"B" },
{ q:"Allah Maha Mendengar disebut?", A:"As-Sami", B:"Al-Basir", C:"Al-Aziz", D:"Al-Halim", correct:"A" },
{ q:"Malaikat pencabut nyawa adalah?", A:"Jibril", B:"Izrail", C:"Mikail", D:"Israfil", correct:"B" },
{ q:"Hari kiamat disebut juga?", A:"Yaumul Akhir", B:"Yaumul Hisab", C:"Yaumul Jaza", D:"Semua benar", correct:"D" },
{ q:"Allah Maha Pencipta disebut?", A:"Al-Khaliq", B:"Al-Alim", C:"Al-Hakim", D:"Al-Aziz", correct:"A" },
{ q:"Iman artinya?", A:"Percaya", B:"Berdoa", C:"Bersedekah", D:"Berpuasa", correct:"A" },
{ q:"Allah tidak beranak dan tidak diperanakkan terdapat dalam surat?", A:"Al-Falaq", B:"An-Nas", C:"Al-Ikhlas", D:"Al-Kautsar", correct:"C" },
{ q:"Malaikat Israfil bertugas?", A:"Meniup sangkakala", B:"Mencabut nyawa", C:"Membagi rezeki", D:"Menyampaikan wahyu", correct:"A" },
{ q:"Malaikat Mikail bertugas?", A:"Meniup sangkakala", B:"Mencabut nyawa", C:"Membagi rezeki", D:"Mencatat amal", correct:"C" },
{ q:"Percaya kepada kitab Allah termasuk rukun iman ke?", A:"2", B:"3", C:"4", D:"5", correct:"B" },
{ q:"Allah Maha Adil disebut?", A:"Al-Adl", B:"Al-Aziz", C:"Al-Halim", D:"Al-Latif", correct:"A" },
{ q:"Jumlah rasul yang wajib diketahui?", A:"10", B:"15", C:"20", D:"25", correct:"D" },
{ q:"Rasul pertama adalah?", A:"Ibrahim", B:"Nuh", C:"Adam", D:"Musa", correct:"C" },
{ q:"Rasul terakhir adalah?", A:"Isa", B:"Muhammad", C:"Musa", D:"Ibrahim", correct:"B" },
{ q:"Allah Maha Bijaksana disebut?", A:"Al-Hakim", B:"Al-Alim", C:"Al-Khaliq", D:"Al-Qadir", correct:"A" },
{ q:"Allah Maha Kuat disebut?", A:"Al-Qawiy", B:"Al-Latif", C:"Al-Halim", D:"Al-Basir", correct:"A" },
{ q:"Allah Maha Lembut disebut?", A:"Al-Latif", B:"Al-Aziz", C:"Al-Qadir", D:"Al-Hakim", correct:"A" },
{ q:"Allah Maha Penyabar disebut?", A:"Al-Halim", B:"Al-Alim", C:"Al-Qawiy", D:"Al-Khaliq", correct:"A" },
{ q:"Percaya kepada malaikat berarti kita harus?", A:"Takut", B:"Meniru kebaikan", C:"Melihat", D:"Menyembah", correct:"B" },
{ q:"Sifat wajib bagi Allah adalah?", A:"Bohong", B:"Lemah", C:"Ada", D:"Tidur", correct:"C" },
{ q:"Allah tidak mungkin mati disebut sifat?", A:"Baqa", B:"Qidam", C:"Mukhalafah", D:"Wahdaniyah", correct:"A" },
{ q:"Allah tidak sama dengan makhluk disebut?", A:"Qidam", B:"Mukhalafah lil hawadits", C:"Baqa", D:"Wahdaniyah", correct:"B" },
{ q:"Allah Maha Berdiri sendiri disebut?", A:"Qiyamuhu binafsih", B:"Baqa", C:"Qidam", D:"Al-Alim", correct:"A" },
{ q:"Allah Maha Esa disebut sifat?", A:"Wahdaniyah", B:"Baqa", C:"Qidam", D:"Qudrah", correct:"A" },
{ q:"Allah Maha Kuasa disebut sifat?", A:"Ilmu", B:"Qudrah", C:"Hayat", D:"Sama", correct:"B" },
{ q:"Allah Maha Mengetahui disebut sifat?", A:"Ilmu", B:"Qudrah", C:"Hayat", D:"Iradah", correct:"A" },
{ q:"Allah Maha Hidup disebut sifat?", A:"Hayat", B:"Ilmu", C:"Qudrah", D:"Iradah", correct:"A" },
{ q:"Allah Maha Berkehendak disebut?", A:"Iradah", B:"Hayat", C:"Ilmu", D:"Qudrah", correct:"A" },
{ q:"Allah Maha Mendengar disebut sifat?", A:"Sama", B:"Basar", C:"Kalam", D:"Qudrah", correct:"A" },
{ q:"Allah Maha Melihat disebut sifat?", A:"Basar", B:"Sama", C:"Kalam", D:"Ilmu", correct:"A" },
{ q:"Allah Maha Berfirman disebut sifat?", A:"Kalam", B:"Ilmu", C:"Hayat", D:"Qudrah", correct:"A" },
{ q:"Allah tidak beranak dan tidak diperanakkan terdapat dalam surat?", A:"Al-Falaq", B:"An-Nas", C:"Al-Ikhlas", D:"Al-Kautsar", correct:"C" },
{ q:"Malaikat Israfil bertugas?", A:"Meniup sangkakala", B:"Mencabut nyawa", C:"Membagi rezeki", D:"Menyampaikan wahyu", correct:"A" },
{ q:"Malaikat Mikail bertugas?", A:"Meniup sangkakala", B:"Mencabut nyawa", C:"Membagi rezeki", D:"Mencatat amal", correct:"C" },
{ q:"Percaya kepada kitab Allah termasuk rukun iman ke?", A:"2", B:"3", C:"4", D:"5", correct:"B" },
{ q:"Allah Maha Adil disebut?", A:"Al-Adl", B:"Al-Aziz", C:"Al-Halim", D:"Al-Latif", correct:"A" },
{ q:"Jumlah rasul yang wajib diketahui?", A:"10", B:"15", C:"20", D:"25", correct:"D" },
{ q:"Rasul pertama adalah?", A:"Ibrahim", B:"Nuh", C:"Adam", D:"Musa", correct:"C" },
{ q:"Rasul terakhir adalah?", A:"Isa", B:"Muhammad", C:"Musa", D:"Ibrahim", correct:"B" },
{ q:"Allah Maha Bijaksana disebut?", A:"Al-Hakim", B:"Al-Alim", C:"Al-Khaliq", D:"Al-Qadir", correct:"A" },
{ q:"Allah Maha Kuat disebut?", A:"Al-Qawiy", B:"Al-Latif", C:"Al-Halim", D:"Al-Basir", correct:"A" },
{ q:"Allah Maha Lembut disebut?", A:"Al-Latif", B:"Al-Aziz", C:"Al-Qadir", D:"Al-Hakim", correct:"A" },
{ q:"Allah Maha Penyabar disebut?", A:"Al-Halim", B:"Al-Alim", C:"Al-Qawiy", D:"Al-Khaliq", correct:"A" },
{ q:"Percaya kepada malaikat berarti kita harus?", A:"Takut", B:"Meniru kebaikan", C:"Melihat", D:"Menyembah", correct:"B" },
{ q:"Sifat wajib bagi Allah adalah?", A:"Bohong", B:"Lemah", C:"Ada", D:"Tidur", correct:"C" },
{ q:"Allah tidak mungkin mati disebut sifat?", A:"Baqa", B:"Qidam", C:"Mukhalafah", D:"Wahdaniyah", correct:"A" },
{ q:"Allah tidak sama dengan makhluk disebut?", A:"Qidam", B:"Mukhalafah lil hawadits", C:"Baqa", D:"Wahdaniyah", correct:"B" },
{ q:"Allah Maha Berdiri sendiri disebut?", A:"Qiyamuhu binafsih", B:"Baqa", C:"Qidam", D:"Al-Alim", correct:"A" },
{ q:"Allah Maha Esa disebut sifat?", A:"Wahdaniyah", B:"Baqa", C:"Qidam", D:"Qudrah", correct:"A" },
{ q:"Allah Maha Kuasa disebut sifat?", A:"Ilmu", B:"Qudrah", C:"Hayat", D:"Sama", correct:"B" },
{ q:"Allah Maha Mengetahui disebut sifat?", A:"Ilmu", B:"Qudrah", C:"Hayat", D:"Iradah", correct:"A" },
{ q:"Allah Maha Hidup disebut sifat?", A:"Hayat", B:"Ilmu", C:"Qudrah", D:"Iradah", correct:"A" },
{ q:"Allah Maha Berkehendak disebut?", A:"Iradah", B:"Hayat", C:"Ilmu", D:"Qudrah", correct:"A" },
{ q:"Allah Maha Mendengar disebut sifat?", A:"Sama", B:"Basar", C:"Kalam", D:"Qudrah", correct:"A" },
{ q:"Allah Maha Melihat disebut sifat?", A:"Basar", B:"Sama", C:"Kalam", D:"Ilmu", correct:"A" },
{ q:"Allah Maha Berfirman disebut sifat?", A:"Kalam", B:"Ilmu", C:"Hayat", D:"Qudrah", correct:"A" },
{ q:"Allah ada tanpa permulaan disebut?", A:"Baqa", B:"Qidam", C:"Wahdaniyah", D:"Qudrah", correct:"B" },
{ q:"Allah kekal selamanya disebut?", A:"Qidam", B:"Baqa", C:"Ilmu", D:"Iradah", correct:"B" },
{ q:"Allah tidak membutuhkan makhluk disebut?", A:"Qiyamuhu binafsih", B:"Baqa", C:"Qudrah", D:"Ilmu", correct:"A" },
{ q:"Allah Maha Menentukan disebut?", A:"Iradah", B:"Qudrah", C:"Ilmu", D:"Hayat", correct:"A" },
{ q:"Sifat mustahil bagi Allah adalah?", A:"Ada", B:"Lemah", C:"Kuasa", D:"Hidup", correct:"B" },
{ q:"Allah tidak mungkin bodoh karena memiliki sifat?", A:"Qudrah", B:"Ilmu", C:"Hayat", D:"Iradah", correct:"B" },
{ q:"Percaya kepada qada dan qadar membuat kita?", A:"Putus asa", B:"Sombong", C:"Sabar", D:"Malas", correct:"C" },
{ q:"Segala sesuatu terjadi atas kehendak?", A:"Manusia", B:"Malaikat", C:"Allah", D:"Nabi", correct:"C" },
{ q:"Qada artinya?", A:"Ketentuan Allah", B:"Usaha manusia", C:"Doa", D:"Takdir baik", correct:"A" },
{ q:"Qadar artinya?", A:"Pelaksanaan ketentuan", B:"Doa", C:"Usaha", D:"Niat", correct:"A" },
{ q:"Contoh takdir muallaq adalah?", A:"Kematian", B:"Rezeki", C:"Jenis kelamin", D:"Kelahiran", correct:"B" },
{ q:"Takdir mubram tidak dapat?", A:"Dilihat", B:"Dihindari", C:"Diketahui", D:"Dipelajari", correct:"B" },
{ q:"Allah Maha Teliti disebut?", A:"Al-Khabir", B:"Al-Alim", C:"Al-Hakim", D:"Al-Qadir", correct:"A" },
{ q:"Allah Maha Tinggi disebut?", A:"Al-Aliyy", B:"Al-Kabir", C:"Al-Aziz", D:"Al-Halim", correct:"A" },
{ q:"Allah Maha Besar disebut?", A:"Al-Kabir", B:"Al-Aliyy", C:"Al-Qawiy", D:"Al-Hakim", correct:"A" },
{ q:"Allah Maha Perkasa disebut?", A:"Al-Aziz", B:"Al-Latif", C:"Al-Halim", D:"Al-Alim", correct:"A" },
{ q:"Allah Maha Mengetahui segala sesuatu?", A:"Al-Alim", B:"Al-Qadir", C:"Al-Hakim", D:"Al-Latif", correct:"A" },
{ q:"Percaya kepada hari akhir membuat kita?", A:"Malas", B:"Rajin beribadah", C:"Sombong", D:"Takut manusia", correct:"B" },
{ q:"Balasan amal baik adalah?", A:"Neraka", B:"Surga", C:"Dosa", D:"Siksa", correct:"B" },
{ q:"Balasan amal buruk adalah?", A:"Surga", B:"Pahala", C:"Neraka", D:"Rahmat", correct:"C" },
{ q:"Allah Maha Mengatur disebut?", A:"Al-Mudabbir", B:"Al-Hakim", C:"Al-Alim", D:"Al-Qadir", correct:"A" },
{ q:"Allah Maha Pengampun disebut?", A:"Al-Ghafur", B:"Al-Aziz", C:"Al-Halim", D:"Al-Latif", correct:"A" },
{ q:"Allah Maha Pemberi rezeki disebut?", A:"Ar-Razzaq", B:"Al-Qadir", C:"Al-Alim", D:"Al-Hakim", correct:"A" },
{ q:"Allah Maha Menjaga disebut?", A:"Al-Hafizh", B:"Al-Aziz", C:"Al-Kabir", D:"Al-Halim", correct:"A" },
{ q:"Allah Maha Menghidupkan disebut?", A:"Al-Muhyi", B:"Al-Mumit", C:"Al-Qadir", D:"Al-Alim", correct:"A" },
{ q:"Allah Maha Mematikan disebut?", A:"Al-Muhyi", B:"Al-Mumit", C:"Al-Qadir", D:"Al-Alim", correct:"B" },
{ q:"Allah Maha Memberi manfaat disebut?", A:"An-Nafi'", B:"Ad-Darr", C:"Al-Hakim", D:"Al-Aziz", correct:"A" },
{ q:"Allah Maha Memberi mudarat disebut?", A:"An-Nafi'", B:"Ad-Darr", C:"Al-Alim", D:"Al-Latif", correct:"B" },
{ q:"Allah Maha Pemberi petunjuk disebut?", A:"Al-Hadi", B:"Al-Alim", C:"Al-Hakim", D:"Al-Qadir", correct:"A" },
{ q:"Allah Maha Cahaya disebut?", A:"An-Nur", B:"Al-Aziz", C:"Al-Kabir", D:"Al-Halim", correct:"A" },
{ q:"Allah Maha Mengetahui yang gaib?", A:"Al-Alim", B:"Al-Ghaib", C:"Al-Khabir", D:"Al-Hakim", correct:"C" },
{ q:"Percaya kepada Allah berarti kita harus?", A:"Menyembah-Nya", B:"Takut manusia", C:"Malas", D:"Sombong", correct:"A" },
{ q:"Contoh iman kepada malaikat adalah?", A:"Tidak percaya", B:"Meniru kebaikan", C:"Menyembah", D:"Melihat", correct:"B" },
{ q:"Contoh iman kepada rasul adalah?", A:"Mengikuti ajaran", B:"Menolak", C:"Menghina", D:"Melupakan", correct:"A" },
{ q:"Contoh iman kepada kitab adalah?", A:"Membaca Al-Qur'an", B:"Membuang", C:"Mengabaikan", D:"Merusak", correct:"A" },
{ q:"Contoh iman kepada hari akhir adalah?", A:"Berbuat baik", B:"Malas", C:"Sombong", D:"Curang", correct:"A" },
{ q:"Contoh iman kepada takdir adalah?", A:"Putus asa", B:"Sabar", C:"Marah", D:"Sombong", correct:"B" },
{ q:"Allah Maha Cepat menghitung amal disebut?", A:"Al-Hasib", B:"Al-Alim", C:"Al-Hakim", D:"Al-Qadir", correct:"A" },
{ q:"Allah Maha Menyaksikan disebut?", A:"Asy-Syahid", B:"Al-Aziz", C:"Al-Kabir", D:"Al-Halim", correct:"A" },
{ q:"Allah Maha Melindungi disebut?", A:"Al-Waliyy", B:"Al-Alim", C:"Al-Hakim", D:"Al-Qadir", correct:"A" },
{ q:"Allah Maha Terpuji disebut?", A:"Al-Hamid", B:"Al-Aziz", C:"Al-Kabir", D:"Al-Halim", correct:"A" },
{ q:"Allah Maha Menghitung disebut?", A:"Al-Muhsi", B:"Al-Alim", C:"Al-Hakim", D:"Al-Qadir", correct:"A" },
{ q:"Allah Maha Memulai penciptaan disebut?", A:"Al-Mubdi'", B:"Al-Mu'id", C:"Al-Hakim", D:"Al-Alim", correct:"A" },
{ q:"Allah Maha Mengembalikan disebut?", A:"Al-Mu'id", B:"Al-Mubdi'", C:"Al-Aziz", D:"Al-Halim", correct:"A" },
{ q:"Allah Maha Hidup disebut?", A:"Al-Hayy", B:"Al-Qayyum", C:"Al-Alim", D:"Al-Hakim", correct:"A" },
{ q:"Allah Maha Berdiri sendiri disebut?", A:"Al-Qayyum", B:"Al-Hayy", C:"Al-Aziz", D:"Al-Kabir", correct:"A" },
{ q:"Allah Maha Penolong disebut?", A:"An-Nasir", B:"Al-Aziz", C:"Al-Halim", D:"Al-Kabir", correct:"A" },
{ q:"Allah Maha Dekat disebut?", A:"Al-Qarib", B:"Al-Alim", C:"Al-Hakim", D:"Al-Qadir", correct:"A" },
{ q:"Allah Maha Mengabulkan doa disebut?", A:"Al-Mujib", B:"Al-Aziz", C:"Al-Halim", D:"Al-Kabir", correct:"A" },
{ q:"Allah Maha Luas rahmat-Nya disebut?", A:"Al-Wasi'", B:"Al-Alim", C:"Al-Hakim", D:"Al-Qadir", correct:"A" }

];