window.arab = [

{ q:"Apa arti 'Kitab'?", A:"Rumah", B:"Buku", C:"Sekolah", D:"Pena", correct:"B" },
{ q:"Apa arti 'Qalam'?", A:"Meja", B:"Kursi", C:"Pena", D:"Pintu", correct:"C" },
{ q:"Apa arti 'Bait'?", A:"Rumah", B:"Buku", C:"Pena", D:"Sekolah", correct:"A" },
{ q:"Apa arti 'Madrasah'?", A:"Rumah", B:"Sekolah", C:"Pena", D:"Buku", correct:"B" },
{ q:"Apa arti 'Walid'?", A:"Ibu", B:"Ayah", C:"Anak", D:"Guru", correct:"B" },
{ q:"Apa arti 'Umm'?", A:"Ayah", B:"Ibu", C:"Guru", D:"Teman", correct:"B" },
{ q:"Apa arti 'Akh'?", A:"Saudara laki-laki", B:"Saudara perempuan", C:"Ayah", D:"Ibu", correct:"A" },
{ q:"Apa arti 'Ukht'?", A:"Saudara laki-laki", B:"Saudara perempuan", C:"Teman", D:"Guru", correct:"B" },
{ q:"Apa arti 'Maa'?", A:"Api", B:"Air", C:"Tanah", D:"Udara", correct:"B" },
{ q:"Apa arti 'Nar'?", A:"Air", B:"Api", C:"Angin", D:"Tanah", correct:"B" },

{ q:"Apa arti 'Syams'?", A:"Bulan", B:"Bintang", C:"Matahari", D:"Langit", correct:"C" },
{ q:"Apa arti 'Qamar'?", A:"Matahari", B:"Bulan", C:"Langit", D:"Bintang", correct:"B" },
{ q:"Apa arti 'Najm'?", A:"Bintang", B:"Bulan", C:"Langit", D:"Air", correct:"A" },
{ q:"Apa arti 'Samaa'?", A:"Bumi", B:"Langit", C:"Air", D:"Api", correct:"B" },
{ q:"Apa arti 'Ardh'?", A:"Langit", B:"Bumi", C:"Air", D:"Api", correct:"B" },
{ q:"Apa arti 'Bab'?", A:"Pintu", B:"Jendela", C:"Meja", D:"Kursi", correct:"A" },
{ q:"Apa arti 'Syubbak'?", A:"Pintu", B:"Jendela", C:"Kursi", D:"Meja", correct:"B" },
{ q:"Apa arti 'Kursi'?", A:"Meja", B:"Kursi", C:"Pintu", D:"Buku", correct:"B" },
{ q:"Apa arti 'Maktab'?", A:"Meja", B:"Kursi", C:"Buku", D:"Rumah", correct:"A" },
{ q:"Apa arti 'Tholib'?", A:"Guru", B:"Murid", C:"Ayah", D:"Teman", correct:"B" },

{ q:"Apa arti 'Mu'allim'?", A:"Murid", B:"Guru", C:"Ayah", D:"Teman", correct:"B" },
{ q:"Apa arti 'Shodiq'?", A:"Teman", B:"Guru", C:"Ayah", D:"Anak", correct:"A" },
{ q:"Apa arti 'Walad'?", A:"Anak laki-laki", B:"Anak perempuan", C:"Ayah", D:"Ibu", correct:"A" },
{ q:"Apa arti 'Bint'?", A:"Anak laki-laki", B:"Anak perempuan", C:"Guru", D:"Teman", correct:"B" },
{ q:"Apa arti 'Yad'?", A:"Kaki", B:"Tangan", C:"Kepala", D:"Mata", correct:"B" },
{ q:"Apa arti 'Ain'?", A:"Telinga", B:"Mata", C:"Hidung", D:"Mulut", correct:"B" },
{ q:"Apa arti 'Udzun'?", A:"Mata", B:"Hidung", C:"Telinga", D:"Mulut", correct:"C" },
{ q:"Apa arti 'Anf'?", A:"Mata", B:"Telinga", C:"Hidung", D:"Mulut", correct:"C" },
{ q:"Apa arti 'Fam'?", A:"Mulut", B:"Hidung", C:"Mata", D:"Kaki", correct:"A" },
{ q:"Apa arti 'Rijl'?", A:"Tangan", B:"Kaki", C:"Kepala", D:"Mata", correct:"B" },

{ q:"Apa arti 'Raas'?", A:"Kepala", B:"Tangan", C:"Kaki", D:"Mata", correct:"A" },
{ q:"Apa arti 'Lisan'?", A:"Tangan", B:"Lidah", C:"Kaki", D:"Mata", correct:"B" },
{ q:"Apa arti 'Kalb'?", A:"Otak", B:"Hati", C:"Tangan", D:"Kaki", correct:"B" },
{ q:"Apa arti 'Baydh'?", A:"Merah", B:"Putih", C:"Hitam", D:"Hijau", correct:"B" },
{ q:"Apa arti 'Aswad'?", A:"Putih", B:"Merah", C:"Hitam", D:"Hijau", correct:"C" },
{ q:"Apa arti 'Ahmar'?", A:"Merah", B:"Putih", C:"Hitam", D:"Hijau", correct:"A" },
{ q:"Apa arti 'Akhdar'?", A:"Hijau", B:"Merah", C:"Putih", D:"Hitam", correct:"A" },
{ q:"Apa arti 'Azraq'?", A:"Hijau", B:"Biru", C:"Merah", D:"Putih", correct:"B" },
{ q:"Apa arti 'Kabir'?", A:"Kecil", B:"Besar", C:"Panjang", D:"Pendek", correct:"B" },
{ q:"Apa arti 'Shaghir'?", A:"Besar", B:"Kecil", C:"Panjang", D:"Pendek", correct:"B" },

{ q:"Apa arti 'Thawil'?", A:"Pendek", B:"Panjang", C:"Kecil", D:"Besar", correct:"B" },
{ q:"Apa arti 'Qashir'?", A:"Panjang", B:"Pendek", C:"Kecil", D:"Besar", correct:"B" },
{ q:"Apa arti 'Jadid'?", A:"Baru", B:"Lama", C:"Cepat", D:"Lambat", correct:"A" },
{ q:"Apa arti 'Qadim'?", A:"Baru", B:"Lama", C:"Cepat", D:"Lambat", correct:"B" },
{ q:"Apa arti 'Sari'?", A:"Cepat", B:"Lambat", C:"Kecil", D:"Besar", correct:"A" },
{ q:"Apa arti 'Bathi'?", A:"Cepat", B:"Lambat", C:"Kecil", D:"Besar", correct:"B" },
{ q:"Apa arti 'Na'am'?", A:"Tidak", B:"Ya", C:"Mungkin", D:"Tidak tahu", correct:"B" },
{ q:"Apa arti 'Laa'?", A:"Ya", B:"Tidak", C:"Mungkin", D:"Tidak tahu", correct:"B" },
{ q:"Apa arti 'Min'?", A:"Dari", B:"Ke", C:"Di", D:"Dengan", correct:"A" },
{ q:"Apa arti 'Ila'?", A:"Dari", B:"Ke", C:"Di", D:"Dengan", correct:"B" },

{ q:"Apa arti 'Fi'?", A:"Di", B:"Ke", C:"Dari", D:"Dengan", correct:"A" },
{ q:"Apa arti 'Ma'a'?", A:"Dengan", B:"Di", C:"Ke", D:"Dari", correct:"A" },
{ q:"Apa arti 'Ala'?", A:"Di atas", B:"Di bawah", C:"Di dalam", D:"Di luar", correct:"A" },
{ q:"Apa arti 'Tahta'?", A:"Di atas", B:"Di bawah", C:"Di dalam", D:"Di luar", correct:"B" },
{ q:"Apa arti 'Dakhil'?", A:"Di luar", B:"Di dalam", C:"Di atas", D:"Di bawah", correct:"B" },
{ q:"Apa arti 'Kharij'?", A:"Di dalam", B:"Di luar", C:"Di atas", D:"Di bawah", correct:"B" },
{ q:"Apa arti 'Yaum'?", A:"Hari", B:"Malam", C:"Pagi", D:"Sore", correct:"A" },
{ q:"Apa arti 'Lail'?", A:"Siang", B:"Malam", C:"Pagi", D:"Sore", correct:"B" },
{ q:"Apa arti 'Shobah'?", A:"Pagi", B:"Malam", C:"Siang", D:"Sore", correct:"A" },
{ q:"Apa arti 'Masaa'?", A:"Pagi", B:"Malam", C:"Sore", D:"Siang", correct:"C" },

{ q:"Apa arti 'Sabahul khair'?", A:"Selamat pagi", B:"Selamat malam", C:"Selamat sore", D:"Selamat siang", correct:"A" },
{ q:"Apa arti 'Masaaul khair'?", A:"Selamat pagi", B:"Selamat malam", C:"Selamat sore", D:"Selamat siang", correct:"C" },
{ q:"Apa arti 'Kaifa haluk?'?", A:"Siapa kamu?", B:"Bagaimana kabarmu?", C:"Di mana kamu?", D:"Apa ini?", correct:"B" },
{ q:"Apa arti 'Ana bikhair'?", A:"Saya sedih", B:"Saya baik", C:"Saya lapar", D:"Saya pergi", correct:"B" },
{ q:"Apa arti 'Man anta?'?", A:"Apa ini?", B:"Siapa kamu?", C:"Di mana kamu?", D:"Kapan kamu?", correct:"B" },
{ q:"Apa arti 'Aina?'?", A:"Kapan?", B:"Di mana?", C:"Siapa?", D:"Apa?", correct:"B" },
{ q:"Apa arti 'Mata?'?", A:"Siapa?", B:"Kapan?", C:"Di mana?", D:"Apa?", correct:"B" },
{ q:"Apa arti 'Maadza?'?", A:"Apa?", B:"Siapa?", C:"Kapan?", D:"Di mana?", correct:"A" },
{ q:"Apa arti 'Limaadza?'?", A:"Kenapa?", B:"Siapa?", C:"Kapan?", D:"Di mana?", correct:"A" },
{ q:"Apa arti 'Kam?'?", A:"Berapa?", B:"Kapan?", C:"Siapa?", D:"Di mana?", correct:"A" },

{ q:"Apa arti 'Wahid'?", A:"Satu", B:"Dua", C:"Tiga", D:"Empat", correct:"A" },
{ q:"Apa arti 'Itsnain'?", A:"Satu", B:"Dua", C:"Tiga", D:"Empat", correct:"B" },
{ q:"Apa arti 'Tsalatsah'?", A:"Tiga", B:"Empat", C:"Lima", D:"Enam", correct:"A" },
{ q:"Apa arti 'Arba'ah'?", A:"Empat", B:"Lima", C:"Enam", D:"Tujuh", correct:"A" },
{ q:"Apa arti 'Khamsah'?", A:"Lima", B:"Enam", C:"Tujuh", D:"Delapan", correct:"A" },
{ q:"Apa arti 'Sittah'?", A:"Enam", B:"Tujuh", C:"Delapan", D:"Sembilan", correct:"A" },
{ q:"Apa arti 'Sab'ah'?", A:"Tujuh", B:"Delapan", C:"Sembilan", D:"Sepuluh", correct:"A" },
{ q:"Apa arti 'Tsamaniyah'?", A:"Delapan", B:"Sembilan", C:"Sepuluh", D:"Sebelas", correct:"A" },
{ q:"Apa arti 'Tis'ah'?", A:"Sembilan", B:"Sepuluh", C:"Sebelas", D:"Dua belas", correct:"A" },
{ q:"Apa arti 'Asyrah'?", A:"Sepuluh", B:"Sembilan", C:"Delapan", D:"Tujuh", correct:"A" },

{ q:"Apa arti 'Yaktub'?", A:"Menulis", B:"Membaca", C:"Makan", D:"Minum", correct:"A" },
{ q:"Apa arti 'Yaqra'?", A:"Menulis", B:"Membaca", C:"Makan", D:"Minum", correct:"B" },
{ q:"Apa arti 'Ya'kul'?", A:"Makan", B:"Minum", C:"Tidur", D:"Duduk", correct:"A" },
{ q:"Apa arti 'Yasyrab'?", A:"Makan", B:"Minum", C:"Tidur", D:"Duduk", correct:"B" },
{ q:"Apa arti 'Yajlis'?", A:"Berdiri", B:"Duduk", C:"Tidur", D:"Makan", correct:"B" },
{ q:"Apa arti 'Yaqif'?", A:"Duduk", B:"Berdiri", C:"Tidur", D:"Makan", correct:"B" },
{ q:"Apa arti 'Yanaam'?", A:"Tidur", B:"Bangun", C:"Duduk", D:"Berdiri", correct:"A" },
{ q:"Apa arti 'Yadhhab'?", A:"Datang", B:"Pergi", C:"Duduk", D:"Tidur", correct:"B" },
{ q:"Apa arti 'Yaji''?", A:"Pergi", B:"Datang", C:"Duduk", D:"Tidur", correct:"B" },
{ q:"Apa arti 'Yal'ab'?", A:"Belajar", B:"Bermain", C:"Makan", D:"Minum", correct:"B" },

{ q:"Apa arti 'Yadrus'?", A:"Belajar", B:"Bermain", C:"Makan", D:"Minum", correct:"A" },
{ q:"Apa arti 'Yafham'?", A:"Mengerti", B:"Tidak tahu", C:"Melihat", D:"Mendengar", correct:"A" },
{ q:"Apa arti 'Yasma''?", A:"Melihat", B:"Mendengar", C:"Berjalan", D:"Berlari", correct:"B" },
{ q:"Apa arti 'Yanzhur'?", A:"Melihat", B:"Mendengar", C:"Berjalan", D:"Berlari", correct:"A" },
{ q:"Apa arti 'Yamsyi'?", A:"Berjalan", B:"Berlari", C:"Duduk", D:"Tidur", correct:"A" },
{ q:"Apa arti 'Yajri'?", A:"Berjalan", B:"Berlari", C:"Duduk", D:"Tidur", correct:"B" },
{ q:"Apa arti 'Yaftah'?", A:"Membuka", B:"Menutup", C:"Makan", D:"Minum", correct:"A" },
{ q:"Apa arti 'Yughliq'?", A:"Membuka", B:"Menutup", C:"Makan", D:"Minum", correct:"B" },
{ q:"Apa arti 'Yarkab'?", A:"Naik", B:"Turun", C:"Duduk", D:"Tidur", correct:"A" },
{ q:"Apa arti 'Yanzil'?", A:"Naik", B:"Turun", C:"Duduk", D:"Tidur", correct:"B" }

];