window.fiqih = [

{ q:"Sholat wajib sehari semalam berapa kali?", A:"3", B:"4", C:"5", D:"6", correct:"C" },
{ q:"Sholat Subuh terdiri dari berapa rakaat?", A:"2", B:"3", C:"4", D:"5", correct:"A" },
{ q:"Sholat Dzuhur terdiri dari?", A:"2", B:"3", C:"4", D:"5", correct:"C" },
{ q:"Sholat Ashar terdiri dari?", A:"2", B:"3", C:"4", D:"5", correct:"C" },
{ q:"Sholat Maghrib terdiri dari?", A:"2", B:"3", C:"4", D:"5", correct:"B" },
{ q:"Sholat Isya terdiri dari?", A:"2", B:"3", C:"4", D:"5", correct:"C" },
{ q:"Sebelum sholat harus?", A:"Makan", B:"Wudhu", C:"Tidur", D:"Main", correct:"B" },
{ q:"Menghadap kiblat adalah?", A:"Sunnah", B:"Rukun sholat", C:"Makruh", D:"Haram", correct:"B" },
{ q:"Takbir pertama dalam sholat disebut?", A:"Takbir biasa", B:"Takbir ihram", C:"Takbir sunnah", D:"Takbir wajib", correct:"B" },
{ q:"Membaca Al-Fatihah hukumnya?", A:"Sunnah", B:"Wajib", C:"Makruh", D:"Haram", correct:"B" },

{ q:"Ruku dilakukan dengan posisi?", A:"Duduk", B:"Berdiri", C:"Membungkuk", D:"Tidur", correct:"C" },
{ q:"Sujud dilakukan dengan?", A:"Kaki", B:"Tangan", C:"Dahi", D:"Kepala", correct:"C" },
{ q:"Duduk di antara dua sujud disebut?", A:"Iftirasy", B:"Ruku", C:"Takbir", D:"Qiyam", correct:"A" },
{ q:"Salam adalah tanda?", A:"Mulai sholat", B:"Akhir sholat", C:"Ruku", D:"Sujud", correct:"B" },
{ q:"Puasa wajib dilakukan pada bulan?", A:"Syawal", B:"Ramadhan", C:"Dzulhijjah", D:"Muharram", correct:"B" },
{ q:"Puasa dimulai dari?", A:"Subuh", B:"Dzuhur", C:"Ashar", D:"Maghrib", correct:"A" },
{ q:"Puasa berakhir saat?", A:"Subuh", B:"Dzuhur", C:"Maghrib", D:"Isya", correct:"C" },
{ q:"Makan sebelum puasa disebut?", A:"Buka", B:"Sahur", C:"Zakat", D:"Doa", correct:"B" },
{ q:"Makan setelah puasa disebut?", A:"Sahur", B:"Buka", C:"Sholat", D:"Doa", correct:"B" },
{ q:"Orang yang tidak puasa wajib?", A:"Sedekah", B:"Qadha", C:"Tidur", D:"Main", correct:"B" },

{ q:"Zakat fitrah dikeluarkan saat?", A:"Idul Fitri", B:"Idul Adha", C:"Ramadhan awal", D:"Setiap hari", correct:"A" },
{ q:"Zakat fitrah berupa?", A:"Uang", B:"Emas", C:"Beras", D:"Baju", correct:"C" },
{ q:"Orang yang wajib zakat disebut?", A:"Mustahik", B:"Muzakki", C:"Amil", D:"Fakir", correct:"B" },
{ q:"Penerima zakat disebut?", A:"Muzakki", B:"Mustahik", C:"Amil", D:"Hakim", correct:"B" },
{ q:"Haji wajib bagi yang?", A:"Kaya", B:"Mampu", C:"Sakit", D:"Miskin", correct:"B" },
{ q:"Haji dilakukan di kota?", A:"Madinah", B:"Mekkah", C:"Jeddah", D:"Riyadh", correct:"B" },
{ q:"Ihram adalah?", A:"Pakaian haji", B:"Makan", C:"Minum", D:"Tidur", correct:"A" },
{ q:"Tawaf adalah?", A:"Lari", B:"Mengelilingi Ka'bah", C:"Duduk", D:"Tidur", correct:"B" },
{ q:"Sa'i adalah?", A:"Lari kecil", B:"Diam", C:"Duduk", D:"Tidur", correct:"A" },
{ q:"Wuquf dilakukan di?", A:"Mina", B:"Arafah", C:"Mekkah", D:"Madinah", correct:"B" },

{ q:"Wudhu menggunakan?", A:"Tanah", B:"Air", C:"Minyak", D:"Pasir", correct:"B" },
{ q:"Membasuh muka termasuk?", A:"Sunnah", B:"Rukun wudhu", C:"Makruh", D:"Haram", correct:"B" },
{ q:"Membasuh tangan sampai siku adalah?", A:"Rukun", B:"Sunnah", C:"Makruh", D:"Haram", correct:"A" },
{ q:"Mengusap kepala adalah?", A:"Rukun", B:"Sunnah", C:"Makruh", D:"Haram", correct:"A" },
{ q:"Membasuh kaki sampai mata kaki adalah?", A:"Rukun", B:"Sunnah", C:"Makruh", D:"Haram", correct:"A" },
{ q:"Tayamum dilakukan jika?", A:"Ada air", B:"Tidak ada air", C:"Banyak air", D:"Air panas", correct:"B" },
{ q:"Tayamum menggunakan?", A:"Air", B:"Tanah", C:"Minyak", D:"Pasir basah", correct:"B" },
{ q:"Sholat berjamaah lebih utama dari?", A:"Sendiri", B:"Duduk", C:"Tidur", D:"Main", correct:"A" },
{ q:"Pemimpin sholat disebut?", A:"Makmum", B:"Imam", C:"Khatib", D:"Muadzin", correct:"B" },
{ q:"Pengikut imam disebut?", A:"Imam", B:"Makmum", C:"Khatib", D:"Muadzin", correct:"B" },

{ q:"Adzan adalah?", A:"Panggilan sholat", B:"Doa makan", C:"Doa tidur", D:"Dzikir", correct:"A" },
{ q:"Iqamah dibaca sebelum?", A:"Tidur", B:"Sholat", C:"Makan", D:"Belajar", correct:"B" },
{ q:"Sholat Jumat wajib bagi?", A:"Wanita", B:"Laki-laki", C:"Anak kecil", D:"Orang sakit", correct:"B" },
{ q:"Sholat Jumat dilakukan pada hari?", A:"Senin", B:"Rabu", C:"Jumat", D:"Sabtu", correct:"C" },
{ q:"Khutbah dilakukan sebelum?", A:"Sholat Jumat", B:"Sholat Subuh", C:"Sholat Maghrib", D:"Sholat Isya", correct:"A" },
{ q:"Jumlah khutbah Jumat ada?", A:"1", B:"2", C:"3", D:"4", correct:"B" },
{ q:"Sholat Id dilakukan saat?", A:"Hari raya", B:"Malam hari", C:"Subuh", D:"Dzuhur", correct:"A" },
{ q:"Sholat Id ada berapa rakaat?", A:"1", B:"2", C:"3", D:"4", correct:"B" },
{ q:"Qurban dilakukan saat?", A:"Idul Fitri", B:"Idul Adha", C:"Ramadhan", D:"Muharram", correct:"B" },
{ q:"Hewan qurban adalah?", A:"Kucing", B:"Kambing", C:"Ayam", D:"Ikan", correct:"B" },

{ q:"Sholat sunnah rawatib dilakukan?", A:"Setelah makan", B:"Sebelum/ sesudah sholat wajib", C:"Saat tidur", D:"Saat main", correct:"B" },
{ q:"Sholat tahajud dilakukan?", A:"Siang", B:"Malam", C:"Pagi", D:"Sore", correct:"B" },
{ q:"Sholat dhuha dilakukan?", A:"Pagi", B:"Siang", C:"Sore", D:"Malam", correct:"A" },
{ q:"Sedekah adalah?", A:"Memberi", B:"Mengambil", C:"Mencuri", D:"Menyimpan", correct:"A" },
{ q:"Hal yang membatalkan puasa?", A:"Tidur", B:"Makan", C:"Diam", D:"Duduk", correct:"B" },
{ q:"Hal yang tidak membatalkan puasa?", A:"Makan", B:"Minum", C:"Tidur", D:"Muntah sengaja", correct:"C" },
{ q:"Sholat tanpa wudhu hukumnya?", A:"Sah", B:"Tidak sah", C:"Makruh", D:"Boleh", correct:"B" },
{ q:"Menutup aurat dalam sholat hukumnya?", A:"Sunnah", B:"Wajib", C:"Makruh", D:"Haram", correct:"B" },
{ q:"Aurat laki-laki adalah?", A:"Dada", B:"Pusar ke lutut", C:"Kepala", D:"Tangan", correct:"B" },
{ q:"Aurat perempuan adalah?", A:"Kepala saja", B:"Seluruh tubuh kecuali wajah dan tangan", C:"Kaki saja", D:"Dada", correct:"B" },

{ q:"Niat dilakukan di?", A:"Mulut", B:"Hati", C:"Tangan", D:"Kaki", correct:"B" },
{ q:"Takbiratul ihram dilakukan dengan?", A:"Diam", B:"Angkat tangan", C:"Duduk", D:"Tidur", correct:"B" },
{ q:"Ruku diikuti dengan?", A:"Sujud", B:"Iktidal", C:"Duduk", D:"Salam", correct:"B" },
{ q:"Iktidal adalah?", A:"Duduk", B:"Berdiri setelah ruku", C:"Sujud", D:"Salam", correct:"B" },
{ q:"Tasyahud akhir dilakukan sebelum?", A:"Ruku", B:"Salam", C:"Sujud", D:"Takbir", correct:"B" },
{ q:"Sholat tanpa niat hukumnya?", A:"Sah", B:"Tidak sah", C:"Makruh", D:"Boleh", correct:"B" },
{ q:"Air suci untuk wudhu disebut?", A:"Najis", B:"Air mutlak", C:"Air kotor", D:"Air bekas", correct:"B" },
{ q:"Najis harus?", A:"Dibiarkan", B:"Dibersihkan", C:"Dibuang", D:"Dilihat", correct:"B" },
{ q:"Bersuci sebelum ibadah disebut?", A:"Wudhu", B:"Taharah", C:"Sholat", D:"Puasa", correct:"B" },
{ q:"Bersih dari hadas disebut?", A:"Najis", B:"Taharah", C:"Kotor", D:"Makruh", correct:"B" },

{ q:"Air yang boleh digunakan untuk wudhu adalah?", A:"Air kotor", B:"Air mutlak", C:"Air najis", D:"Air bekas", correct:"B" },
{ q:"Jika tidak ada air, bersuci dilakukan dengan?", A:"Wudhu", B:"Tayamum", C:"Mandi", D:"Istinja", correct:"B" },
{ q:"Mengusap sepatu dalam wudhu disebut?", A:"Tayamum", B:"Mash", C:"Sujud", D:"Iktidal", correct:"B" },
{ q:"Sholat yang dikerjakan sendiri disebut?", A:"Berjamaah", B:"Munfarid", C:"Jama'", D:"Qashar", correct:"B" },
{ q:"Sholat yang dilakukan bersama-sama disebut?", A:"Munfarid", B:"Berjamaah", C:"Sendiri", D:"Qashar", correct:"B" },
{ q:"Orang yang mengumandangkan adzan disebut?", A:"Imam", B:"Makmum", C:"Muadzin", D:"Khatib", correct:"C" },
{ q:"Sholat qashar artinya?", A:"Dipercepat", B:"Dipendekkan", C:"Diperbanyak", D:"Ditunda", correct:"B" },
{ q:"Sholat jama' artinya?", A:"Dipisah", B:"Digabung", C:"Dipendekkan", D:"Ditinggal", correct:"B" },
{ q:"Puasa sunnah dilakukan selain bulan?", A:"Ramadhan", B:"Syawal", C:"Dzulhijjah", D:"Semua benar", correct:"A" },
{ q:"Puasa Senin Kamis termasuk puasa?", A:"Wajib", B:"Sunnah", C:"Makruh", D:"Haram", correct:"B" },

{ q:"Zakat mal adalah zakat?", A:"Fitrah", B:"Harta", C:"Makanan", D:"Beras", correct:"B" },
{ q:"Nisab zakat artinya?", A:"Jumlah minimal", B:"Jumlah maksimal", C:"Waktu zakat", D:"Jenis zakat", correct:"A" },
{ q:"Orang yang berhak menerima zakat disebut?", A:"Muzakki", B:"Mustahik", C:"Amil", D:"Imam", correct:"B" },
{ q:"Haji dilakukan pada bulan?", A:"Ramadhan", B:"Dzulhijjah", C:"Syawal", D:"Rajab", correct:"B" },
{ q:"Umrah bisa dilakukan?", A:"Kapan saja", B:"Hanya Ramadhan", C:"Hanya haji", D:"Hanya Syawal", correct:"A" },
{ q:"Melempar jumrah dilakukan di?", A:"Mekkah", B:"Mina", C:"Arafah", D:"Madinah", correct:"B" },
{ q:"Tahallul adalah?", A:"Memotong rambut", B:"Lari", C:"Duduk", D:"Tidur", correct:"A" },
{ q:"Ihram dimulai dari?", A:"Miqat", B:"Masjid", C:"Rumah", D:"Pasar", correct:"A" },
{ q:"Hewan qurban disembelih pada?", A:"Idul Fitri", B:"Idul Adha", C:"Ramadhan", D:"Muharram", correct:"B" },
{ q:"Daging qurban dibagikan kepada?", A:"Orang kaya", B:"Orang miskin", C:"Teman saja", D:"Diri sendiri", correct:"B" },

{ q:"Sholat witir dilakukan pada waktu?", A:"Pagi", B:"Malam", C:"Siang", D:"Sore", correct:"B" },
{ q:"Jumlah rakaat witir minimal?", A:"1", B:"2", C:"3", D:"4", correct:"A" },
{ q:"Sholat tarawih dilakukan saat?", A:"Ramadhan", B:"Syawal", C:"Dzulhijjah", D:"Muharram", correct:"A" },
{ q:"Mandi wajib dilakukan saat?", A:"Hadas besar", B:"Hadas kecil", C:"Tidur", D:"Makan", correct:"A" },
{ q:"Contoh hadas besar adalah?", A:"Kentut", B:"Buang air kecil", C:"Junub", D:"Tidur", correct:"C" },
{ q:"Contoh hadas kecil adalah?", A:"Junub", B:"Buang air kecil", C:"Haid", D:"Nifas", correct:"B" },
{ q:"Istinja adalah?", A:"Bersuci setelah buang air", B:"Sholat", C:"Puasa", D:"Zakat", correct:"A" },
{ q:"Air najis tidak boleh digunakan untuk?", A:"Minum", B:"Wudhu", C:"Mandi", D:"Semua benar", correct:"D" },
{ q:"Sholat tepat waktu hukumnya?", A:"Sunnah", B:"Wajib", C:"Makruh", D:"Haram", correct:"B" },
{ q:"Orang yang meninggalkan sholat termasuk?", A:"Baik", B:"Dosa", C:"Pahala", D:"Biasa", correct:"B" }

];