window.quran = [

{ q:"Al-Qur'an adalah kitab suci umat?", A:"Kristen", B:"Islam", C:"Hindu", D:"Budha", correct:"B" },
{ q:"Al-Qur'an diturunkan kepada Nabi?", A:"Musa", B:"Isa", C:"Muhammad", D:"Ibrahim", correct:"C" },
{ q:"Al-Qur'an diturunkan melalui malaikat?", A:"Mikail", B:"Jibril", C:"Israfil", D:"Izrail", correct:"B" },
{ q:"Bahasa Al-Qur'an adalah?", A:"Indonesia", B:"Arab", C:"Inggris", D:"Latin", correct:"B" },
{ q:"Al-Qur'an diturunkan di kota?", A:"Madinah", B:"Mekkah", C:"Thaif", D:"Yaman", correct:"B" },
{ q:"Surat pertama dalam Al-Qur'an adalah?", A:"Al-Baqarah", B:"Al-Fatihah", C:"An-Nas", D:"Al-Ikhlas", correct:"B" },
{ q:"Surat terakhir dalam Al-Qur'an adalah?", A:"Al-Falaq", B:"An-Nas", C:"Al-Ikhlas", D:"Al-Kautsar", correct:"B" },
{ q:"Jumlah surat dalam Al-Qur'an ada?", A:"100", B:"110", C:"114", D:"120", correct:"C" },
{ q:"Al-Qur'an terdiri dari berapa juz?", A:"20", B:"25", C:"30", D:"35", correct:"C" },
{ q:"Surat Al-Fatihah terdiri dari berapa ayat?", A:"5", B:"6", C:"7", D:"8", correct:"C" },

{ q:"Surat terpanjang dalam Al-Qur'an adalah?", A:"Al-Fatihah", B:"Al-Baqarah", C:"An-Nas", D:"Al-Ikhlas", correct:"B" },
{ q:"Surat terpendek dalam Al-Qur'an adalah?", A:"Al-Kautsar", B:"Al-Fatihah", C:"An-Nas", D:"Al-Ikhlas", correct:"A" },
{ q:"Al-Qur'an berisi petunjuk bagi?", A:"Muslim", B:"Semua manusia", C:"Anak-anak", D:"Orang tua", correct:"B" },
{ q:"Membaca Al-Qur'an mendapat?", A:"Dosa", B:"Pahala", C:"Marah", D:"Sedih", correct:"B" },
{ q:"Orang yang membaca Al-Qur'an disebut?", A:"Qari", B:"Guru", C:"Imam", D:"Penulis", correct:"A" },
{ q:"Hafal Al-Qur'an disebut?", A:"Qari", B:"Hafidz", C:"Imam", D:"Muadzin", correct:"B" },
{ q:"Surat Al-Ikhlas menjelaskan tentang?", A:"Kiamat", B:"Tauhid", C:"Zakat", D:"Puasa", correct:"B" },
{ q:"Surat An-Nas termasuk surat?", A:"Pendek", B:"Panjang", C:"Sedang", D:"Tidak ada", correct:"A" },
{ q:"Surat Al-Falaq berbicara tentang?", A:"Perang", B:"Perlindungan", C:"Zakat", D:"Haji", correct:"B" },
{ q:"Al-Qur'an diturunkan secara?", A:"Sekaligus", B:"Bertahap", C:"Sebagian", D:"Acak", correct:"B" },

{ q:"Orang yang menulis Al-Qur'an disebut?", A:"Penulis wahyu", B:"Imam", C:"Guru", D:"Muadzin", correct:"A" },
{ q:"Tempat menyimpan Al-Qur'an disebut?", A:"Rak", B:"Lemari", C:"Mushaf", D:"Kitab", correct:"C" },
{ q:"Membaca Al-Qur'an dengan tartil artinya?", A:"Cepat", B:"Pelan dan benar", C:"Keras", D:"Acak", correct:"B" },
{ q:"Al-Qur'an sebagai pedoman hidup disebut?", A:"Kitab", B:"Hidayah", C:"Petunjuk", D:"Semua benar", correct:"D" },
{ q:"Kita harus membaca Al-Qur'an dengan?", A:"Main-main", B:"Serius", C:"Acuh", D:"Marah", correct:"B" },

{ q:"Surat Al-Fatihah disebut juga?", A:"Ummul Kitab", B:"An-Nas", C:"Al-Ikhlas", D:"Al-Kautsar", correct:"A" },
{ q:"Ayat pertama Al-Qur'an adalah?", A:"Alhamdulillah", B:"Bismillah", C:"Iqra", D:"Allah", correct:"C" },
{ q:"Wahyu pertama turun di gua?", A:"Tsur", B:"Hira", C:"Uhud", D:"Arafah", correct:"B" },
{ q:"Surat Al-Baqarah berarti?", A:"Sapi", B:"Kambing", C:"Ayam", D:"Ikan", correct:"A" },
{ q:"Surat Al-Kautsar berarti?", A:"Nikmat banyak", B:"Sedikit", C:"Air", D:"Api", correct:"A" },

{ q:"Surat An-Nas berarti?", A:"Manusia", B:"Langit", C:"Bumi", D:"Air", correct:"A" },
{ q:"Surat Al-Falaq berarti?", A:"Subuh", B:"Malam", C:"Siang", D:"Petang", correct:"A" },
{ q:"Surat Al-Ikhlas berarti?", A:"Ikhlas", B:"Sabar", C:"Syukur", D:"Doa", correct:"A" },
{ q:"Surat Al-Asr berbicara tentang?", A:"Waktu", B:"Air", C:"Api", D:"Tanah", correct:"A" },
{ q:"Surat Al-Kafirun tentang?", A:"Orang beriman", B:"Orang kafir", C:"Anak", D:"Guru", correct:"B" },

{ q:"Surat Al-Ma'un mengajarkan tentang?", A:"Kebaikan", B:"Keburukan", C:"Makanan", D:"Minuman", correct:"A" },
{ q:"Surat Al-Qadr menjelaskan tentang?", A:"Malam Lailatul Qadr", B:"Hari kiamat", C:"Zakat", D:"Puasa", correct:"A" },
{ q:"Surat Al-Zalzalah tentang?", A:"Gempa", B:"Air", C:"Api", D:"Angin", correct:"A" },
{ q:"Surat Al-Adiyat tentang?", A:"Kuda", B:"Air", C:"Api", D:"Tanah", correct:"A" },
{ q:"Surat Al-Takatsur tentang?", A:"Kesombongan", B:"Kebaikan", C:"Air", D:"Api", correct:"A" },

{ q:"Surat Al-Humazah tentang?", A:"Pencela", B:"Orang baik", C:"Guru", D:"Anak", correct:"A" },
{ q:"Surat Al-Fiil tentang?", A:"Gajah", B:"Kuda", C:"Sapi", D:"Ayam", correct:"A" },
{ q:"Surat Quraisy tentang?", A:"Suku Quraisy", B:"Guru", C:"Anak", D:"Orang tua", correct:"A" },
{ q:"Surat Al-Kausar terdiri dari?", A:"3 ayat", B:"4 ayat", C:"5 ayat", D:"6 ayat", correct:"A" },
{ q:"Surat An-Nas terdiri dari?", A:"5 ayat", B:"6 ayat", C:"7 ayat", D:"8 ayat", correct:"B" },

{ q:"Al-Qur'an dibaca dengan ilmu?", A:"Tajwid", B:"Matematika", C:"IPA", D:"IPS", correct:"A" },
{ q:"Tajwid adalah ilmu membaca?", A:"Hadits", B:"Al-Qur'an", C:"Fiqih", D:"Sejarah", correct:"B" },
{ q:"Huruf hijaiyah berjumlah?", A:"26", B:"28", C:"30", D:"32", correct:"B" },
{ q:"Huruf pertama hijaiyah adalah?", A:"Ba", B:"Alif", C:"Ta", D:"Jim", correct:"B" },
{ q:"Huruf terakhir hijaiyah adalah?", A:"Ya", B:"Nun", C:"Lam", D:"Mim", correct:"A" },

{ q:"Al-Qur'an harus dibaca dengan?", A:"Main-main", B:"Adab", C:"Marah", D:"Acuh", correct:"B" },
{ q:"Sebelum membaca Al-Qur'an kita harus?", A:"Tidur", B:"Wudhu", C:"Makan", D:"Main", correct:"B" },
{ q:"Al-Qur'an tidak boleh diletakkan di?", A:"Tempat tinggi", B:"Tempat kotor", C:"Rak", D:"Meja", correct:"B" },
{ q:"Kita harus menjaga Al-Qur'an dengan?", A:"Baik", B:"Buruk", C:"Acuh", D:"Marah", correct:"A" },
{ q:"Mendengarkan Al-Qur'an harus?", A:"Bermain", B:"Diam", C:"Berisik", D:"Lari", correct:"B" },

{ q:"Al-Qur'an diturunkan selama?", A:"10 tahun", B:"20 tahun", C:"23 tahun", D:"30 tahun", correct:"C" },
{ q:"Al-Qur'an sebagai rahmat bagi?", A:"Muslim", B:"Semua manusia", C:"Anak-anak", D:"Guru", correct:"B" },
{ q:"Orang yang menghafal Al-Qur'an disebut?", A:"Hafidz", B:"Qari", C:"Guru", D:"Imam", correct:"A" },
{ q:"Membaca Al-Qur'an setiap hari termasuk?", A:"Buruk", B:"Terpuji", C:"Tercela", D:"Biasa", correct:"B" },
{ q:"Al-Qur'an diturunkan untuk?", A:"Main", B:"Petunjuk hidup", C:"Tidur", D:"Marah", correct:"B" },

{ q:"Surat Yasin sering dibaca pada?", A:"Pagi", B:"Malam Jumat", C:"Siang", D:"Sore", correct:"B" },
{ q:"Surat Al-Mulk terdiri dari?", A:"20 ayat", B:"30 ayat", C:"40 ayat", D:"50 ayat", correct:"B" },
{ q:"Al-Qur'an harus dijaga dari?", A:"Kotor", B:"Air", C:"Api", D:"Semua benar", correct:"D" },
{ q:"Al-Qur'an adalah mukjizat Nabi?", A:"Musa", B:"Isa", C:"Muhammad", D:"Ibrahim", correct:"C" },
{ q:"Mukjizat terbesar Nabi Muhammad adalah?", A:"Tongkat", B:"Al-Qur'an", C:"Api", D:"Air", correct:"B" },

{ q:"Al-Qur'an mengajarkan tentang?", A:"Kebaikan", B:"Keburukan", C:"Permusuhan", D:"Kesombongan", correct:"A" },
{ q:"Kita membaca Al-Qur'an untuk?", A:"Pahala", B:"Dosa", C:"Marah", D:"Sedih", correct:"A" },
{ q:"Al-Qur'an harus dipelajari sejak?", A:"Tua", B:"Kecil", C:"Dewasa", D:"Lansia", correct:"B" },
{ q:"Al-Qur'an tidak boleh dirusak karena?", A:"Kitab suci", B:"Buku biasa", C:"Kertas", D:"Tulisan", correct:"A" },
{ q:"Membaca Al-Qur'an harus dengan?", A:"Lalai", B:"Khusyuk", C:"Marah", D:"Acuh", correct:"B" },

{ q:"Al-Qur'an diturunkan sebagai?", A:"Cerita", B:"Petunjuk", C:"Mainan", D:"Game", correct:"B" },
{ q:"Orang yang tidak membaca Al-Qur'an akan?", A:"Rugi", B:"Untung", C:"Bahagia", D:"Kaya", correct:"A" },
{ q:"Al-Qur'an berisi hukum?", A:"Islam", B:"Matematika", C:"IPA", D:"IPS", correct:"A" },
{ q:"Al-Qur'an harus diamalkan dalam?", A:"Hidup", B:"Main", C:"Tidur", D:"Makan", correct:"A" },
{ q:"Al-Qur'an memberi kita?", A:"Petunjuk", B:"Kebingungan", C:"Kesedihan", D:"Marah", correct:"A" },

{ q:"Surat Al-Fatihah wajib dibaca dalam?", A:"Puasa", B:"Sholat", C:"Zakat", D:"Haji", correct:"B" },
{ q:"Al-Qur'an diturunkan pada bulan?", A:"Syawal", B:"Ramadhan", C:"Muharram", D:"Rajab", correct:"B" },
{ q:"Lailatul Qadr terdapat pada bulan?", A:"Syawal", B:"Ramadhan", C:"Dzulhijjah", D:"Muharram", correct:"B" },
{ q:"Surat Al-Qadr menceritakan tentang?", A:"Hari kiamat", B:"Malam kemuliaan", C:"Perang", D:"Zakat", correct:"B" },
{ q:"Al-Qur'an pertama kali dikumpulkan pada masa?", A:"Umar", B:"Abu Bakar", C:"Utsman", D:"Ali", correct:"B" },

{ q:"Al-Qur'an disempurnakan penulisannya pada masa?", A:"Abu Bakar", B:"Umar", C:"Utsman", D:"Ali", correct:"C" },
{ q:"Orang yang menulis wahyu disebut?", A:"Muadzin", B:"Penulis wahyu", C:"Imam", D:"Qari", correct:"B" },
{ q:"Surat dalam Al-Qur'an ada 114 disebut?", A:"Juz", B:"Ayat", C:"Surat", D:"Kitab", correct:"C" },
{ q:"Setiap surat terdiri dari?", A:"Huruf", B:"Ayat", C:"Kata", D:"Kalimat", correct:"B" },
{ q:"Ayat dalam Al-Qur'an jumlahnya sekitar?", A:"5000", B:"6000+", C:"7000", D:"8000", correct:"B" },

{ q:"Al-Qur'an adalah mukjizat yang?", A:"Biasa", B:"Abadi", C:"Sementara", D:"Pendek", correct:"B" },
{ q:"Al-Qur'an tidak berubah sampai?", A:"Sekarang", B:"Besok", C:"Kemarin", D:"Nanti", correct:"A" },
{ q:"Membaca Al-Qur'an harus dalam keadaan?", A:"Kotor", B:"Suci", C:"Marah", D:"Lapar", correct:"B" },
{ q:"Al-Qur'an harus dihormati karena?", A:"Buku biasa", B:"Kitab suci", C:"Tulisan", D:"Kertas", correct:"B" },
{ q:"Kita membaca Al-Qur'an untuk mendapatkan?", A:"Uang", B:"Pahala", C:"Main", D:"Tidur", correct:"B" },

{ q:"Al-Qur'an diturunkan sebagai peringatan bagi?", A:"Orang kaya", B:"Semua manusia", C:"Anak-anak", D:"Guru", correct:"B" },
{ q:"Al-Qur'an mengajarkan kita untuk?", A:"Berbuat baik", B:"Berbuat jahat", C:"Malas", D:"Sombong", correct:"A" },
{ q:"Orang yang mempelajari Al-Qur'an adalah?", A:"Buruk", B:"Baik", C:"Jahat", D:"Sombong", correct:"B" },
{ q:"Menghafal Al-Qur'an termasuk amalan?", A:"Buruk", B:"Mulia", C:"Biasa", D:"Tidak penting", correct:"B" },
{ q:"Al-Qur'an harus diamalkan dalam kehidupan?", A:"Sehari-hari", B:"Kadang", C:"Jarang", D:"Tidak perlu", correct:"A" },

{ q:"Mendengarkan Al-Qur'an harus dengan sikap?", A:"Berisik", B:"Tenang", C:"Main", D:"Lari", correct:"B" },
{ q:"Al-Qur'an tidak boleh diinjak karena?", A:"Buku biasa", B:"Kitab suci", C:"Kertas", D:"Tulisan", correct:"B" },
{ q:"Al-Qur'an memberi kita petunjuk ke jalan?", A:"Salah", B:"Benar", C:"Gelap", D:"Sulit", correct:"B" },
{ q:"Al-Qur'an mengajarkan kita untuk beriman kepada?", A:"Allah", B:"Manusia", C:"Harta", D:"Dunia", correct:"A" },
{ q:"Membaca Al-Qur'an dengan tartil artinya?", A:"Cepat", B:"Pelan dan benar", C:"Keras", D:"Acak", correct:"B" }

];