window.tarikh = [

{ q:"Nabi terakhir adalah?", A:"Nabi Isa", B:"Nabi Musa", C:"Nabi Muhammad", D:"Nabi Ibrahim", correct:"C" },
{ q:"Nabi Muhammad lahir di kota?", A:"Madinah", B:"Mekkah", C:"Thaif", D:"Jeddah", correct:"B" },
{ q:"Ayah Nabi Muhammad bernama?", A:"Abu Thalib", B:"Abdullah", C:"Abdul Muthalib", D:"Hamzah", correct:"B" },
{ q:"Ibu Nabi Muhammad bernama?", A:"Khadijah", B:"Aisyah", C:"Aminah", D:"Fatimah", correct:"C" },
{ q:"Kakek Nabi Muhammad adalah?", A:"Abu Thalib", B:"Abdul Muthalib", C:"Umar", D:"Ali", correct:"B" },
{ q:"Nabi Muhammad diangkat menjadi rasul pada usia?", A:"30", B:"35", C:"40", D:"45", correct:"C" },
{ q:"Wahyu pertama turun di gua?", A:"Hira", B:"Tsur", C:"Uhud", D:"Arafah", correct:"A" },
{ q:"Malaikat yang menyampaikan wahyu adalah?", A:"Mikail", B:"Israfil", C:"Jibril", D:"Izrail", correct:"C" },
{ q:"Kitab suci Nabi Muhammad adalah?", A:"Taurat", B:"Injil", C:"Zabur", D:"Al-Qur'an", correct:"D" },
{ q:"Peristiwa hijrah Nabi ke Madinah terjadi pada tahun?", A:"1 H", B:"2 H", C:"3 H", D:"4 H", correct:"A" },

{ q:"Sahabat Nabi yang pertama masuk Islam adalah?", A:"Umar", B:"Ali", C:"Abu Bakar", D:"Utsman", correct:"C" },
{ q:"Istri pertama Nabi Muhammad adalah?", A:"Aisyah", B:"Khadijah", C:"Fatimah", D:"Hafshah", correct:"B" },
{ q:"Anak perempuan Nabi Muhammad bernama?", A:"Aisyah", B:"Fatimah", C:"Khadijah", D:"Hafshah", correct:"B" },
{ q:"Masjid pertama yang dibangun Nabi adalah?", A:"Masjidil Haram", B:"Masjid Nabawi", C:"Masjid Quba", D:"Masjid Aqsa", correct:"C" },
{ q:"Masjid Nabi di Madinah adalah?", A:"Masjid Quba", B:"Masjid Nabawi", C:"Masjid Haram", D:"Masjid Aqsa", correct:"B" },
{ q:"Perang Badar terjadi pada tahun?", A:"1 H", B:"2 H", C:"3 H", D:"4 H", correct:"B" },
{ q:"Perang Uhud terjadi setelah perang?", A:"Badar", B:"Khandaq", C:"Tabuk", D:"Hunain", correct:"A" },
{ q:"Perang Khandaq disebut juga perang?", A:"Parit", B:"Air", C:"Gunung", D:"Pasir", correct:"A" },
{ q:"Kota tempat Nabi wafat adalah?", A:"Mekkah", B:"Madinah", C:"Thaif", D:"Jeddah", correct:"B" },
{ q:"Nabi wafat pada usia?", A:"60", B:"61", C:"62", D:"63", correct:"D" },

{ q:"Khalifah pertama setelah Nabi adalah?", A:"Umar", B:"Ali", C:"Abu Bakar", D:"Utsman", correct:"C" },
{ q:"Khalifah kedua adalah?", A:"Umar", B:"Ali", C:"Utsman", D:"Abu Bakar", correct:"A" },
{ q:"Khalifah ketiga adalah?", A:"Ali", B:"Umar", C:"Utsman", D:"Abu Bakar", correct:"C" },
{ q:"Khalifah keempat adalah?", A:"Ali", B:"Umar", C:"Utsman", D:"Abu Bakar", correct:"A" },
{ q:"Empat khalifah disebut?", A:"Khulafaur Rasyidin", B:"Sahabat", C:"Tabi'in", D:"Ulama", correct:"A" },
{ q:"Gua tempat Nabi bersembunyi saat hijrah adalah?", A:"Hira", B:"Tsur", C:"Uhud", D:"Arafah", correct:"B" },
{ q:"Sahabat yang menemani Nabi saat hijrah adalah?", A:"Umar", B:"Ali", C:"Abu Bakar", D:"Utsman", correct:"C" },
{ q:"Perjanjian Hudaibiyah terjadi di?", A:"Mekkah", B:"Madinah", C:"Hudaibiyah", D:"Thaif", correct:"C" },
{ q:"Fathu Mekkah artinya?", A:"Perang Mekkah", B:"Penaklukan Mekkah", C:"Hijrah ke Mekkah", D:"Masuk Mekkah", correct:"B" },
{ q:"Ka'bah dibersihkan dari berhala saat?", A:"Hijrah", B:"Badar", C:"Fathu Mekkah", D:"Uhud", correct:"C" },

{ q:"Nabi Musa diutus kepada?", A:"Bani Israil", B:"Quraisy", C:"Romawi", D:"Persia", correct:"A" },
{ q:"Nabi Isa lahir tanpa?", A:"Ayah", B:"Ibu", C:"Saudara", D:"Guru", correct:"A" },
{ q:"Nabi Ibrahim dikenal sebagai?", A:"Khalilullah", B:"Rasulullah", C:"Habibullah", D:"Nabiullah", correct:"A" },
{ q:"Nabi Nuh membuat?", A:"Masjid", B:"Kapal", C:"Rumah", D:"Kota", correct:"B" },
{ q:"Nabi Yusuf terkenal karena?", A:"Kekuatan", B:"Kecerdasan", C:"Ketampanan", D:"Kekayaan", correct:"C" },
{ q:"Abu Bakar bergelar?", A:"Al-Faruq", B:"As-Siddiq", C:"Dzun Nurain", D:"Asadullah", correct:"B" },
{ q:"Umar bin Khattab bergelar?", A:"As-Siddiq", B:"Al-Faruq", C:"Dzun Nurain", D:"Asadullah", correct:"B" },
{ q:"Utsman bin Affan bergelar?", A:"As-Siddiq", B:"Al-Faruq", C:"Dzun Nurain", D:"Asadullah", correct:"C" },
{ q:"Ali bin Abi Thalib bergelar?", A:"Asadullah", B:"Al-Faruq", C:"Dzun Nurain", D:"As-Siddiq", correct:"A" },
{ q:"Abu Bakar adalah sahabat Nabi yang?", A:"Paling kaya", B:"Pertama masuk Islam", C:"Paling kuat", D:"Paling muda", correct:"B" },

{ q:"Umar bin Khattab terkenal karena?", A:"Kekayaan", B:"Keberanian", C:"Kecerdasan", D:"Kebaikan", correct:"B" },
{ q:"Utsman bin Affan terkenal karena?", A:"Kedermawanan", B:"Kekuatan", C:"Kecerdasan", D:"Keberanian", correct:"A" },
{ q:"Ali bin Abi Thalib adalah sepupu Nabi?", A:"Ya", B:"Tidak", C:"Kadang", D:"Tidak tahu", correct:"A" },
{ q:"Perang pertama dalam Islam adalah?", A:"Uhud", B:"Badar", C:"Khandaq", D:"Tabuk", correct:"B" },
{ q:"Perang Uhud terjadi di dekat gunung?", A:"Hira", B:"Uhud", C:"Tsur", D:"Arafah", correct:"B" },
{ q:"Perang Khandaq terjadi karena?", A:"Serangan musuh", B:"Perjanjian", C:"Hijrah", D:"Perdagangan", correct:"A" },
{ q:"Khalifah Abu Bakar memerangi kaum?", A:"Musyrik", B:"Murtad", C:"Yahudi", D:"Nasrani", correct:"B" },
{ q:"Umar bin Khattab wafat karena?", A:"Sakit", B:"Dibunuh", C:"Tua", D:"Perang", correct:"B" },
{ q:"Utsman bin Affan wafat karena?", A:"Sakit", B:"Dibunuh", C:"Perang", D:"Tua", correct:"B" },
{ q:"Ali bin Abi Thalib wafat karena?", A:"Sakit", B:"Dibunuh", C:"Perang", D:"Tua", correct:"B" },

{ q:"Islam berkembang ke Persia pada masa?", A:"Abu Bakar", B:"Umar", C:"Utsman", D:"Ali", correct:"B" },
{ q:"Islam berkembang ke Romawi pada masa?", A:"Abu Bakar", B:"Umar", C:"Utsman", D:"Ali", correct:"B" },
{ q:"Nabi berdakwah secara sembunyi selama?", A:"1 tahun", B:"2 tahun", C:"3 tahun", D:"4 tahun", correct:"C" },
{ q:"Dakwah terang-terangan dimulai setelah?", A:"1 tahun", B:"2 tahun", C:"3 tahun", D:"4 tahun", correct:"C" },
{ q:"Orang Quraisy menolak dakwah Nabi karena?", A:"Takut", B:"Sombong", C:"Lapar", D:"Sedih", correct:"B" },
{ q:"Hijrah berarti?", A:"Perang", B:"Pindah", C:"Diam", D:"Tidur", correct:"B" },
{ q:"Nabi hijrah dari Mekkah ke?", A:"Thaif", B:"Madinah", C:"Jeddah", D:"Yaman", correct:"B" },
{ q:"Nama lain Madinah adalah?", A:"Yatsrib", B:"Mekkah", C:"Thaif", D:"Syam", correct:"A" },
{ q:"Orang yang membantu Nabi di Madinah disebut?", A:"Muhajirin", B:"Anshar", C:"Quraisy", D:"Tabi'in", correct:"B" },
{ q:"Orang yang hijrah disebut?", A:"Anshar", B:"Muhajirin", C:"Quraisy", D:"Tabi'in", correct:"B" },

{ q:"Nabi membangun masjid di Madinah untuk?", A:"Tidur", B:"Ibadah", C:"Makan", D:"Belajar saja", correct:"B" },
{ q:"Piagam Madinah adalah?", A:"Perjanjian", B:"Perang", C:"Bangunan", D:"Kitab", correct:"A" },
{ q:"Nabi mengajarkan persaudaraan antara?", A:"Quraisy", B:"Muhajirin dan Anshar", C:"Yahudi", D:"Nasrani", correct:"B" },
{ q:"Nabi wafat pada hari?", A:"Senin", B:"Selasa", C:"Rabu", D:"Jumat", correct:"A" },
{ q:"Makam Nabi berada di?", A:"Mekkah", B:"Madinah", C:"Thaif", D:"Yaman", correct:"B" },
{ q:"Nabi dikenal sebagai orang yang?", A:"Bohong", B:"Jujur", C:"Kasar", D:"Marah", correct:"B" },
{ q:"Gelar Nabi sebelum diangkat rasul adalah?", A:"Al-Amin", B:"Al-Faruq", C:"As-Siddiq", D:"Dzun Nurain", correct:"A" },
{ q:"Nabi berdagang bersama?", A:"Aisyah", B:"Khadijah", C:"Fatimah", D:"Hafshah", correct:"B" },
{ q:"Nabi menikah dengan Khadijah pada usia?", A:"20", B:"25", C:"30", D:"35", correct:"B" },
{ q:"Khadijah adalah seorang?", A:"Guru", B:"Pedagang", C:"Petani", D:"Penulis", correct:"B" },

{ q:"Nabi memiliki sifat?", A:"Buruk", B:"Mulia", C:"Jahat", D:"Kasar", correct:"B" },
{ q:"Dakwah Nabi mengajarkan?", A:"Kesombongan", B:"Tauhid", C:"Kebencian", D:"Permusuhan", correct:"B" },
{ q:"Nabi selalu bersikap?", A:"Kasar", B:"Lemah lembut", C:"Marah", D:"Sombong", correct:"B" },
{ q:"Nabi melarang perbuatan?", A:"Baik", B:"Buruk", C:"Jujur", D:"Sabar", correct:"B" },
{ q:"Nabi mengajarkan kita untuk?", A:"Berbuat baik", B:"Berbuat jahat", C:"Malas", D:"Sombong", correct:"A" },
{ q:"Nabi Muhammad dikenal sebagai uswatun hasanah artinya?", A:"Contoh buruk", B:"Contoh baik", C:"Orang biasa", D:"Orang kaya", correct:"B" },
{ q:"Orang pertama yang masuk Islam dari kalangan anak-anak adalah?", A:"Umar", B:"Ali", C:"Abu Bakar", D:"Utsman", correct:"B" },
{ q:"Orang pertama yang masuk Islam dari kalangan wanita adalah?", A:"Aisyah", B:"Fatimah", C:"Khadijah", D:"Hafshah", correct:"C" },
{ q:"Orang pertama yang masuk Islam dari kalangan budak adalah?", A:"Bilal", B:"Ali", C:"Umar", D:"Utsman", correct:"A" },
{ q:"Bilal bin Rabah terkenal sebagai?", A:"Pedagang", B:"Muadzin", C:"Penulis", D:"Prajurit", correct:"B" },

{ q:"Abu Jahal adalah?", A:"Sahabat Nabi", B:"Musuh Nabi", C:"Guru Nabi", D:"Keluarga Nabi", correct:"B" },
{ q:"Abu Lahab adalah?", A:"Sahabat Nabi", B:"Musuh Nabi", C:"Guru Nabi", D:"Keluarga Nabi", correct:"B" },
{ q:"Nabi berdakwah di Thaif mendapat?", A:"Sambutan baik", B:"Penolakan", C:"Hadiah", D:"Pujian", correct:"B" },
{ q:"Isra Mi'raj adalah perjalanan Nabi dari?", A:"Mekkah ke Madinah", B:"Mekkah ke Masjid Aqsa", C:"Madinah ke langit", D:"Thaif ke Mekkah", correct:"B" },
{ q:"Isra Mi'raj terjadi pada malam?", A:"Jumat", B:"Sabtu", C:"Senin", D:"Tidak diketahui", correct:"D" },
{ q:"Perintah sholat 5 waktu diterima saat?", A:"Hijrah", B:"Badar", C:"Isra Mi'raj", D:"Uhud", correct:"C" },
{ q:"Sahabat yang menggantikan Nabi saat hijrah di tempat tidur adalah?", A:"Umar", B:"Ali", C:"Abu Bakar", D:"Utsman", correct:"B" },
{ q:"Kaum Quraisy adalah penduduk?", A:"Madinah", B:"Mekkah", C:"Thaif", D:"Yaman", correct:"B" },
{ q:"Anshar berasal dari kota?", A:"Mekkah", B:"Madinah", C:"Thaif", D:"Syam", correct:"B" },
{ q:"Muhajirin berasal dari?", A:"Madinah", B:"Mekkah", C:"Yaman", D:"Syam", correct:"B" },

{ q:"Masjidil Haram berada di?", A:"Madinah", B:"Mekkah", C:"Thaif", D:"Yaman", correct:"B" },
{ q:"Masjid Nabawi berada di?", A:"Mekkah", B:"Madinah", C:"Thaif", D:"Yaman", correct:"B" },
{ q:"Masjid Al-Aqsa berada di?", A:"Mekkah", B:"Madinah", C:"Palestina", D:"Yaman", correct:"C" },
{ q:"Nabi Muhammad wafat pada tahun?", A:"10 H", B:"11 H", C:"12 H", D:"13 H", correct:"B" },
{ q:"Islam masuk ke Indonesia melalui?", A:"Perang", B:"Perdagangan", C:"Penjajahan", D:"Paksaan", correct:"B" },
{ q:"Wali Songo adalah penyebar Islam di?", A:"Arab", B:"Indonesia", C:"India", D:"China", correct:"B" },
{ q:"Sunan Kalijaga adalah salah satu?", A:"Raja", B:"Wali Songo", C:"Pedagang", D:"Tentara", correct:"B" },
{ q:"Islam berkembang dengan cara damai disebut?", A:"Kekerasan", B:"Dakwah", C:"Perang", D:"Paksaan", correct:"B" },
{ q:"Dakwah artinya?", A:"Perang", B:"Mengajak kebaikan", C:"Bermain", D:"Tidur", correct:"B" },
{ q:"Nabi mengajarkan akhlak yang?", A:"Buruk", B:"Mulia", C:"Jahat", D:"Kasar", correct:"B" }

];